 Массив – это совокупность элементов, которые хранятся последовательно в памяти и имеют общий тип данных. Каждому его элементу присвоен собственный индекс, который позволяет обращаться к нему для чтения или изменения го значения.

1. Cоздать список my_list, состоящий из чисел 1,2,3

In [1]:
my_list = [1,2,3]

2. С использованием numpy список my_list преобразовать в одномерный массив

In [2]:
import numpy as np

np.array(my_list)

array([1, 2, 3])

3. Создать вложенный список my_list2, состоящий из [1,2,3],[4,5,6],[7,8,9]

In [3]:
my_list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

4. С использованием numpy список my_list2 преобразовать в двумерный массив

In [4]:
np.array(my_list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

5. С использованием arange сгенерировать одномерный массив, состоящий из 0, 1, 2, 3, 4, 5, 6, 7, 8, 9

In [5]:
print(np.arange(0, 10))

[0 1 2 3 4 5 6 7 8 9]


6. С использованием arange сгенерировать одномерный массив, состоящий из 0,  2,  4,  6,  8, 10

In [6]:
print(np.arange(0, 10, 2))

[0 2 4 6 8]


7. С использованием zeros сгенерировать одномерный массив, состоящий из 0., 0., 0.

In [7]:
print(np.zeros(3))

[0. 0. 0.]


8. С использованием zeros сгенерировать двумерный массив, состоящий из нулей, который распределены в 5 строк и в 5 столбцов

In [8]:
print(np.zeros((5, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


9. С использованием zeros сгенерировать двумерный массив, состоящий из нулей, которые распределены в 2 строки и 3 столбца

In [9]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


10. С использованием ones сгенерировать одномерный массив, состоящий из 4 единиц

In [10]:
np.ones((4))

array([1., 1., 1., 1.])

11. С использованием ones сгенерировать двумерный массив, состоящий из единиц, которые распределены в 3 строки и 4 столбца

In [11]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12. С использованием linspace сгенерировать одномерный массив, в котором содержится 10 чисел в диапазоне от 0 до 5

In [12]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

13. С использованием linspace сгенерировать одномерный массив, в котором содержится 100 чисел в диапазоне от 0 до 5

In [13]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

14. С использованием numpy создать единичную матрицу размером 4

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

15. С использованием random.rand сгенерировать одномерный массив, состоящий из 5 элементов . По какому распределению генерируются числа?

In [15]:
np.random.rand(5)

array([0.42696926, 0.09323966, 0.51032192, 0.66010347, 0.0058791 ])

16.  С использованием random.rand сгенерировать двумерный массив, состоящий из 5 строк и 5 столбцов

In [16]:
np.random.rand(5, 5)

array([[0.95086264, 0.36053585, 0.04649044, 0.2534764 , 0.84081151],
       [0.16529131, 0.53671388, 0.14412732, 0.99950212, 0.61086031],
       [0.06784612, 0.60514945, 0.25366288, 0.27901945, 0.93141581],
       [0.97051072, 0.90119096, 0.67293572, 0.54714933, 0.37241076],
       [0.93401133, 0.43771511, 0.36740741, 0.80782603, 0.04077003]])

17. С использованием random.randn сгенерировать одномерный массив, состоящий из 2 элементов. По какому распределению генерируются числа?

In [17]:
np.random.randn(2)

array([-1.07091383, -0.16792031])

18. С использованием random.randn сгенерировать двумерный массив, состоящий из 5 строк и 5 столбцов 

In [18]:
np.random.randn(5, 5)

array([[-0.63907281,  0.11545157,  0.76710155,  0.83516445,  0.5022038 ],
       [-0.0608537 , -0.15842333,  1.82976394, -0.56597594,  0.92199147],
       [ 0.60092624, -0.93045702,  1.20349634, -0.21960382,  1.42310258],
       [-1.04656095, -1.61501134, -0.92919399, -0.26322312, -0.04217747],
       [ 0.09669736, -0.18043574, -1.64936176, -1.00367484,  1.41145173]])

19. С использованием random.randint сгенерировать одномерный массив из 10 чисел в диапазоне от 1 до 100 

In [19]:
np.random.randint(1, 101, 10)

array([72, 73, 55, 18, 12, 62, 41, 60, 97, 50])

20. С использованием arange создать одномерный массив arr, состоящий из 25 чисел от 0 до 24 включительно 

In [20]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

21. С использованием метода reshape преобразовать одномерный массив arr в двумерный , состоящий из 5 строк и 5 столбцов

In [21]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

22. с использованием методов argmin и argmax  вывести минимальное и максимальное значения в arr

In [22]:
min_value = arr.min()
max_value = arr.max()
print("Минимальное значение:", min_value)
print("Максимальное значение:", max_value)

Минимальное значение: 0
Максимальное значение: 24


23. С использованием arange создать одномерный массив arr в диапазоне от 0 до 11. 

In [23]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


24. Из массива arr создать массив slice_of_arr, который берет элементы с 0 по 6

In [24]:
slice_of_arr = arr[:7]
print(slice_of_arr)

[0 1 2 3 4 5 6]


25. С помощью индексирования все элементы массива  slice_of_arr заменить на 99

In [25]:
slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)

[99 99 99 99 99 99 99]
[99 99 99 99 99 99 99  7  8  9 10 11]


26. Что при этом произошло с массивом arr?

После этой операции slice_of_arr будет содержать только 99, и так как slice_of_arr является срезом arr, изменения также отразятся на arr.

27. Создать массив, состоящий из [5,10,15],[20,25,30],[35,40,45]. Необходимый вывод ниже

In [26]:
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(matrix)

print(matrix[1, 1])  
print(matrix[1, 2])  
print(matrix[2, 1])  

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
25
30
40


28. Вывести по-отдельности значения 25, 30, 40

In [27]:
sub_matrix = matrix[:2, 1:]
print(sub_matrix)

[[10 15]
 [25 30]]


29. Вывести часть матрицы как в примере вывода ниже

In [28]:
arr = np.arange(1, 12)
bool_arr = arr > 5
print(bool_arr)

[False False False False False  True  True  True  True  True  True]


30. Заново создать одномерный массив arr , состоящий из чисел от 1 до 11.

In [32]:
arr = np.arange(1, 12)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

31. Созать bool_arr , который через conditional selection проверяет каждый элемент из массива arr на >5 

In [30]:
bool_arr = arr > 5
print(bool_arr)

[False False False False False  True  True  True  True  True  True]


32. Как с использованием bool_arr вывести в arr значения > 5 

In [31]:
print(arr[bool_arr])

[ 6  7  8  9 10 11]
